# Generated by Django 3.0.5 on 2020-04-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=50)),
                ('current_mileage', models.CharField(max_length=10)),
                ('vehicle_image', models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSeZ5dDmSiPUes1VyS31ITsH2xoMFV8_ihiAQdC9BuCMWkevRXo&usqp=CAU')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=200)),
                ('service_mileage', models.CharField(max_length=10)),
                ('service_dt', models.CharField(max_length=50)),
                ('service_by', models.CharField(max_length=200)),
                ('service_receipt', models.ImageField(null=True, upload_to='images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Log', to='autocare_d.Vehicle')),
            ],
        ),
    ]
